# Part 1 — Inspect & Understand the Dataset

In [12]:
import pandas as pd
df = pd.read_csv("C:\\Users\\deore\\Downloads\\customer_analytics - customer_analytics.csv")

In [13]:
# then display the first 10 rows
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

## Q2. Inspect the end of the dataset

In [14]:
# display the 15 rows
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [15]:
# Q3. Random inspection 

# display 10 random rerecords
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1441,101607,24,228127,32284.26,655,13,Kolkata,Corporate,Agent,2023-01-05 00:00:00,Yes,Medium,43856.34,133,1.5
146,100129,50,unknown,44118.56,667,13,Pune,Corporate,Online,2025-08-11 00:00:00,No,Medium,45092.96,115,8.7
347,101928,70,163440,NaN,445,0,Pune,Corporate,Branch,2021-05-11 00:00:00,Yes,High,4326.03,4,5.6
1667,100914,64,50169,124354.82,608,4,Kolkata,SME,Branch,31/99/2024,Yes,Medium,16280.52,51,5.9
291,101111,NaN,152734,240404.4,427,11,Mumbai,SME,Mobile,2024-02-13 00:00:00,Yes,High,-,20,6.8
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
1632,100798,43,56007,66145.11,318,6,Bangalore,Retail,Online,2021-08-07 00:00:00,Yes,High,49075.75,64,7.8
496,100809,25,56367,242156.8,834,13,Mumbai,NaN,Branch,2022-05-26 00:00:00,Yes,Low,14148.62,134,3.8
1500,101510,71,42073,NaN,NaN,12,Pune,Premium,Branch,2022-05-05 00:00:00,Yes,Low,NaN,54,6.3
1922,100338,65,123818,202754.32,405,7,Mumbai,Premium,Mobile,2025-02-02 00:00:00,No,High,47421.9,24,4.3

In [16]:
# Q4. Dataset audit 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [17]:
# Q5. Missing-value audit 

isnull = df.isnull().sum()
isna = df.isna().sum()

print(isnull.equals(isna))

True

# Part 2 — Detect & Fix Data Quality Problems

In [18]:
# Q6. Duplicate investigation 
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool

In [20]:
# Q7. Remove duplicates 

# drop duplicate rows and store in df 
df = df.drop_duplicates()

# verify that no duplicates exist
print(df.duplicated().sum())

0

In [21]:
# Q8. Numeric column investigation 

# numaric columns
df.select_dtypes(includes ="number")

      Customer_ID  Tenure_Years  Satisfaction_Score
0          101317             3                 3.1
1          101001             8                 8.2
2          101069            12                 6.3
3          101968            14                 9.7
4          100530             4                 3.7
...           ...           ...                 ...
2035       101131            12                 8.6
2036       101295             8                 2.6
2037       100861             8                 1.3
2038       101460             8                 9.3
2039       101127             6                 3.1

[2000 rows x 3 columns]

In [26]:
# identify which columns are numeric
num_cols = df.select_dtypes(include = "number").columns

print("Numeric columns:")
print(num_cols)

Numeric columns:
Index(['Customer_ID', 'Tenure_Years', 'Satisfaction_Score'], dtype='object')

In [30]:
# identify object type coloums

obj_clos = df.select_dtypes(include ="object").columns

print("Object columns:")
print(obj_clos)
list(obj_clos)

Object columns:
Index(['Age', 'Annual_Income', 'Account_Balance', 'Credit_Score', 'City',
       'Segment', 'Channel', 'Join_Date', 'Active', 'Risk_Level',
       'Monthly_Spend', 'Transactions'],
      dtype='object')

['Age',
 'Annual_Income',
 'Account_Balance',
 'Credit_Score',
 'City',
 'Segment',
 'Channel',
 'Join_Date',
 'Active',
 'Risk_Level',
 'Monthly_Spend',
 'Transactions']

In [36]:
# find potentially numeric object columns

for col in obj_clos:
    coverted = pd.to_numeric(df[col], errors = 'coerce')

    # count how many values become numbers
    num_count = coverted.notna().sum()

    if num_count > 0:
        print(f"{col} --> potentially numeric ({num_count} numarice values)")

Age --> potentially numeric (1873 numarice values)
Annual_Income --> potentially numeric (1851 numarice values)
Account_Balance --> potentially numeric (1832 numarice values)
Credit_Score --> potentially numeric (1960 numarice values)
Active --> potentially numeric (28 numarice values)
Monthly_Spend --> potentially numeric (1854 numarice values)
Transactions --> potentially numeric (1960 numarice values)

In [38]:
## Q9. Fix Age 

# convert age to numeric
df['Age'] = pd.to_numeric(df['Age'],errors ='coerce')

# caluclate median age
median_age = df['Age'].median()

# fill missing values with median
df['Age'] = df['Age'].fillna(median_age)

df['Age'].head()

0    55.0
1    32.0
2    23.0
3    66.0
4    67.0
Name: Age, dtype: float64

## Q10. Fix Annual Income

In [39]:
# convert invalid values to missing 
df['Annual_Income'] = pd.to_numeric(df["Annual_Income"],errors = 'coerce')

In [40]:
# convert the column to a numeric datatype
df['Annual_Income'] = df['Annual_Income'].astype(float)

In [41]:
# calculate the median
median_income = df['Annual_Income'].median()

In [42]:
# fill missing values with the median
df['Annual_Income'] = df['Annual_Income'].fillna(median_income)

In [43]:
# verify
print(df['Annual_Income'].head())
print(df['Annual_Income'].dtype)
print(df['Annual_Income'].isna().sum())

0     44033.0
1    215546.0
2    226403.0
3     87824.0
4     31570.0
Name: Annual_Income, dtype: float64
float64
0

# Part 3 — Numerical Cleaning

In [44]:
# covert invalid values to missing 
df['Account_Balance'] = pd.to_numeric(df['Account_Balance'],errors ='coerce')

In [45]:
# calculate the mean Account Balance
mean_bal = df['Account_Balance'].mean()

In [48]:
# fill missing values with mean
df['Account_Balance'] = df['Account_Balance'].fillna(mean_bal)

In [49]:
# verify the result
print(df['Account_Balance'].head())
print(df['Account_Balance'].dtypes)
print(df['Account_Balance'].isna().sum())

0    111350.85
1    254378.37
2    159975.42
3    295741.60
4    242423.78
Name: Account_Balance, dtype: float64
float64
0

# Q12. Clean Credit Score

In [50]:
# convert invalid values to missing
df['Credit_Score'] = pd.to_numeric(df['Credit_Score'], errors = 'coerce')

In [51]:
# calculate the median Credit score
median_score = df['Credit_Score'].median()

In [52]:
# fill missing values with the median
df['Credit_Score'] = df['Credit_Score'].fillna(median_score)

In [53]:
# convert the column to integer
df['Credit_Score'] = df['Credit_Score'].astype(int)

In [56]:
#  verify
print(df['Credit_Score'].head())
print(df['Credit_Score'].dtype)
print(df['Credit_Score'].isna().sum())

0    772
1    374
2    668
3    315
4    370
Name: Credit_Score, dtype: int64
int64
0

# Q13. Clean Monthly Spend

In [68]:
# convert invalid values to missing
df['Monthly_Spend'] = pd.to_numeric(df['Monthly_Spend'], errors = 'coerce')

In [69]:
# calculate the median Credit score
median_score = df['Monthly_Spend'].median()

In [70]:
# replace missing values with the median
df['Monthly_Spend'] = df['Monthly_Spend'].fillna(median_score)

In [71]:
# make sure the final column is numeric

df['Monthly_Spend'] = df['Monthly_Spend'].astype(float)

In [72]:
# verify
print(df['Monthly_Spend'].head())
print(df['Monthly_Spend'].dtype)
print(df['Monthly_Spend'].isna().sum())

0    23066.19
1    24625.17
2    28536.34
3    12869.71
4    34163.02
Name: Monthly_Spend, dtype: float64
float64
0

# Q14. Clean Transactions

In [78]:
# convert invalid values to missing
df['Transactions'] = pd.to_numeric(df['Transactions'], errors = 'coerce')

In [79]:
# calculate the median Credit score
median_score = df['Transactions'].median()

In [80]:
# replace missing values with the median
df['Transactions'] = df['Transactions'].fillna(median_score)

In [81]:
# make sure the final column is numeric

df['Transactions'] = df['Transactions'].astype(int)

In [82]:
# verify
print(df['Transactions'].head())
print(df['Transactions'].dtype)
print(df['Transactions'].isna().sum())

0    135
1    106
2    146
3    115
4     94
Name: Transactions, dtype: int64
int64
0

# Q15. Clean Satisfaction Score

In [ ]:
# convert invalid values to missing
df['Satisfaction_Score'] = pd.to_numeric(df['Satisfaction_Score'], errors = 'coerce')

In [ ]:
# calculate the median Satisfaction score
mean_score = df['Satisfaction_Score'].mean()

In [ ]:
# replace missing values with the median
df['Satisfaction_Score'] = df['Satisfaction_Score'].fillna(mean_score)

In [ ]:
# make sure the final column is numeric

df['Satisfaction_Score'] = df['Satisfaction_Score'].astype(float)

In [83]:
# verify
print(df['Satisfaction_Score'].head())
print(df['Satisfaction_Score'].dtype)
print(df['Satisfaction_Score'].isna().sum())

0    3.1
1    8.2
2    6.3
3    9.7
4    3.7
Name: Satisfaction_Score, dtype: float64
float64
80

# Part 4 — Date Cleaning

# Q16. Investigate Join_Date

In [86]:
# check data type
print(df['Join_Date'].dtype)

object

In [87]:
# count missing values
print("Missing values:",df['Join_Date'].isna().sum())

Missing values: 100

In [88]:
# view unique sample values
print(df['Join_Date'].dropna().head(20))

0     2022-08-15 00:00:00
1     2025-01-11 00:00:00
2     2024-08-01 00:00:00
3     2021-05-15 00:00:00
4     2026-02-03 00:00:00
5     2023-06-04 00:00:00
6     2024-01-16 00:00:00
7     2024-06-26 00:00:00
8     2025-03-12 00:00:00
9     2021-10-07 00:00:00
10    2023-03-02 00:00:00
11    2025-11-22 00:00:00
12    2021-06-25 00:00:00
13    2025-11-19 00:00:00
14    2025-08-26 00:00:00
15    2024-05-05 00:00:00
16    2022-01-07 00:00:00
17    2022-05-25 00:00:00
18    2022-10-07 00:00:00
19    2023-08-10 00:00:00
Name: Join_Date, dtype: object

In [89]:
# find values that may have different formats
print(df['Join_Date'].value_counts().head(20))

Join_Date
not_a_date             11
unknown                 8
31/99/2024              6
2025-10-31 00:00:00     5
2022-06-26 00:00:00     5
2022-07-24 00:00:00     5
2023-07-19 00:00:00     5
2023-12-24 00:00:00     5
2024-01-10 00:00:00     5
2022-06-28 00:00:00     5
2022-01-25 00:00:00     4
2023-07-21 00:00:00     4
2025-01-11 00:00:00     4
2021-05-21 00:00:00     4
2023-08-11 00:00:00     4
2025-06-19 00:00:00     4
2022-02-12 00:00:00     4
2021-09-16 00:00:00     4
2024-08-19 00:00:00     4
2022-07-01 00:00:00     4
Name: count, dtype: int64

In [90]:
# try converting to detetime without changing the original column
test_dates = pd.to_datetime(df['Join_Date'],errors = 'coerce', dayfirst=True)

C:\Users\deore\AppData\Local\Temp\ipykernel_13832\1740622156.py:2: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  test_dates = pd.to_datetime(df['Join_Date'],errors = 'coerce', dayfirst=True)

In [91]:
# invalid date strings
invalid_dates = df.loc[df["Join_Date"].notna() & test_dates.isna(), "Join_Date"]

print("Invalid date strings:")
print(invalid_dates.unique())

Invalid date strings:
['not_a_date' '31/99/2024' 'unknown']

# Q17. Convert Join_Date

In [93]:
# Convert Join_Date to detetime
# invalid daets will become NaT

df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors ='coerce', dayfirst = True)

C:\Users\deore\AppData\Local\Temp\ipykernel_13832\2542076336.py:4: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors ='coerce', dayfirst = True)

In [94]:
# verify
print(df['Join_Date'].head())
print(df['Join_Date'].dtype)
print(df['Join_Date'].isna().sum())

0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
Name: Join_Date, dtype: datetime64[ns]
datetime64[ns]
125

In [95]:
# Count missing dates
missing_dates = df['Join_Date'].isna().sum()
print('Missing dates remaining:', missing_dates)

Missing dates remaining: 125

In [97]:
# Calculate the median date
median_date = df['Join_Date'].median()

In [99]:
# Fill missing dates with the median date
df['Join_Date'] = df['Join_Date'].fillna(median_date)

In [100]:
# Verify that no missing dates remain
print('Missing dates after filling:', df['Join_Date'].isna().sum())

Missing dates after filling: 0

In [101]:
# Display first 5 rows
print(df['Join_Date'].head())

0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
Name: Join_Date, dtype: datetime64[ns]

# Q 18

In [129]:
# Convert to datetime
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')

In [130]:
# Count missing dates
missing_dates = df['Join_Date'].isna().sum()
print('Missing dates after conversion:', missing_dates)

Missing dates after conversion: 0

In [131]:
# Fill missing dates using previous valid date
df['Join_Date'] = df['Join_Date'].fillna(method='ffill')

C:\Users\deore\AppData\Local\Temp\ipykernel_13832\3674096946.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Join_Date'] = df['Join_Date'].fillna(method='ffill')

In [132]:

# If the first rows are still missing, use backward fill
df['Join_Date'] = df['Join_Date'].fillna(method='bfill')

C:\Users\deore\AppData\Local\Temp\ipykernel_13832\264487947.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Join_Date'] = df['Join_Date'].fillna(method='bfill')

In [133]:
# Final check
print('Missing dates after filling:', df['Join_Date'].isna().sum())

Missing dates after filling: 0

In [134]:
# Display sample
print(df['Join_Date'].head(10))

0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
5   2023-06-04
6   2024-01-16
7   2024-06-26
8   2025-03-12
9   2021-10-07
Name: Join_Date, dtype: datetime64[ns]

# Part 5 — Categorical Cleaning

In [102]:
# Check unique frequency distribution
print(df['City'].value_counts())

City
Mumbai       286
Hyderabad    274
Delhi        268
Kolkata      260
Pune         253
Chennai      234
Bangalore    230
mumbai        22
hyderabad     18
bangalore     17
pune          17
delhi         15
kolkata       14
chennai       12
Name: count, dtype: int64

In [103]:
# (Optional) Check unique city names
print(df['City'].unique())

['Bangalore' 'Delhi' 'Chennai' 'Mumbai' 'bangalore' 'Kolkata' 'Hyderabad'
 nan 'Pune' 'chennai' 'kolkata' 'pune' 'hyderabad' 'mumbai' 'delhi']

# 20. Analyze Segment

In [104]:
# Check frequency distribution of Segment
print(df['Segment'].value_counts())

Segment
Premium      516
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

In [105]:
# Check missing values
print('Missing values:', df['Segment'].isna().sum())

Missing values: 100

In [110]:
# Find the most frequent category 
most_common_segment = df['Segment'].value_counts().idxmax()

In [111]:
print('Most common segment:', most_common_segment)

Most common segment: Premium

In [112]:
# Fill missing values with the most appropriate category 
df['Segment'] = df['Segment'].fillna(most_common_segment)

In [113]:
# Verify
print(df['Segment'].isna().sum())
print(df['Segment'].value_counts())

0
Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

# Q21. Clean Active

In [116]:
# Fill missing values with most frequent value
mode_active = df['Active'].mode()[0]
df['Active'] = df['Active'].fillna(mode_active)

In [117]:
# Check result
print(df['Active'].value_counts(dropna=False))
print(df['Active'].head(10))

Active
Yes    1346
No      534
Y        17
0        16
N        16
no       16
NO       15
YES      14
yes      14
1        12
Name: count, dtype: int64
0    Yes
1    Yes
2     No
3    Yes
4     No
5    Yes
6    Yes
7    Yes
8    Yes
9    Yes
Name: Active, dtype: object

In [118]:
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1

## Q22. Clean Risk_Level

In [121]:
# Check missing values in RiskLevel column
print('Missing values in RiskLevel:')
print(df['Risk_Level'].isna().sum())

Missing values in RiskLevel:
0

In [122]:
# Display current class distribution
print('\nCurrent class distribution:')
print(df['Risk_Level'].value_counts(dropna=False))

Current class distribution:
Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64

In [124]:
# Fill missing values with the most frequent class (mode)
mode_class = df['Risk_Level'].mode()[0]
df['Risk_Level'] = df['Risk_Level'].fillna(mode_class)

In [125]:


# Final class distribution
print('\nFinal class distribution:')
print(df['Risk_Level'].value_counts())

Final class distribution:
Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64

In [127]:
# Optional: display percentages
print('\nFinal class distribution (%):')
print(df['Risk_Level'].value_counts(normalize=True) * 100)

Final class distribution (%):
Risk_Level
High      49.3
Low       27.0
Medium    23.7
Name: proportion, dtype: float64

# Part 6 — Column Transformation

In [135]:
# Rename columns
df.rename(columns={
    'Customer_ID': 'Customer_ID',
    'Annual_Income': 'AnnualIncome',
    'Account_Balance': 'AccountBalance',
    'Credit_Score': 'CreditScore',
    'Tenure_Years': 'Tenure',
    'Join_Date': 'CustomerJoinDate',
    'Risk_Level': 'RiskLevel',
    'Monthly_Spend': 'MonthlySpend',
    'Satisfaction_Score': 'SatisfactionScore'
}, inplace=True)

In [136]:
# Display updated column names
print(df.columns)

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore'],
      dtype='object')

# Q24. Add a prefix

In [137]:
# Add prefix to all columns
df = df.add_prefix('Customer_')

In [138]:
# Display updated column names
print(df.columns)

Index(['Customer_Customer_ID', 'Customer_Age', 'Customer_AnnualIncome',
       'Customer_AccountBalance', 'Customer_CreditScore', 'Customer_Tenure',
       'Customer_City', 'Customer_Segment', 'Customer_Channel',
       'Customer_CustomerJoinDate', 'Customer_Active', 'Customer_RiskLevel',
       'Customer_MonthlySpend', 'Customer_Transactions',
       'Customer_SatisfactionScore'],
      dtype='object')

# Q25. Remove unnecessary column

In [140]:
# Create cleaned DataFrame without Customer_ID
df_clean = df.drop('Customer_Customer_ID', axis=1)

In [141]:
# Display remaining columns
print(df_clean.columns)

Index(['Customer_Age', 'Customer_AnnualIncome', 'Customer_AccountBalance',
       'Customer_CreditScore', 'Customer_Tenure', 'Customer_City',
       'Customer_Segment', 'Customer_Channel', 'Customer_CustomerJoinDate',
       'Customer_Active', 'Customer_RiskLevel', 'Customer_MonthlySpend',
       'Customer_Transactions', 'Customer_SatisfactionScore'],
      dtype='object')

In [142]:
# Check shape before and after
print('Original shape:', df.shape)
print('Cleaned shape :', df_clean.shape)

Original shape: (2000, 15)
Cleaned shape : (2000, 14)

# Part 7 — Create New Columns

# .Q26. Create Annual Income in Lakhs

In [145]:
# # Create Income_Lakhs column
df['Income_Lakhs'] = df['Customer_AnnualIncome'] / 100000

In [147]:
# Display first 10 records
print(df[['Customer_AnnualIncome', 'Income_Lakhs']].head(10))

   Customer_AnnualIncome  Income_Lakhs
0                44033.0       0.44033
1               215546.0       2.15546
2               226403.0       2.26403
3                87824.0       0.87824
4                31570.0       0.31570
5                37087.0       0.37087
6                67229.0       0.67229
7               139914.0       1.39914
8               153267.0       1.53267
9               139914.0       1.39914

# Q27. Create Monthly Income

In [148]:
# Create MonthlyIncome
df['MonthlyIncome'] = df['Customer_AnnualIncome'] / 12

In [150]:
# Create Income_After_Spending
df['Income_After_Spending'] = df['MonthlyIncome'] - df['Customer_MonthlySpend']

In [151]:
# Display first 10 records
print(df[['Customer_AnnualIncome', 'Customer_MonthlySpend', 'MonthlyIncome', 'Income_After_Spending']].head(10))

   Customer_AnnualIncome  Customer_MonthlySpend  MonthlyIncome  \
0                44033.0               23066.19    3669.416667
1               215546.0               24625.17   17962.166667
2               226403.0               28536.34   18866.916667
3                87824.0               12869.71    7318.666667
4                31570.0               34163.02    2630.833333
5                37087.0               15121.16    3090.583333
6                67229.0               17655.61    5602.416667
7               139914.0                1720.85   11659.500000
8               153267.0               38043.07   12772.250000
9               139914.0               11472.36   11659.500000

   Income_After_Spending
0          -19396.773333
1           -6663.003333
2           -9669.423333
3           -5551.043333
4          -31532.186667
5          -12030.576667
6          -12053.193333
7            9938.650000
8          -25270.820000
9             187.140000

# Q28. Create Balance-to-Income Ratio

In [156]:
# Create Balance_Income_Ratio safely
df['Balance_Income_Ratio'] = df['Customer_AccountBalance'] / df['Customer_AnnualIncome']

In [154]:
df

,Customer_Customer_ID,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1,0.44033,3669.416667,-19396.773333
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2,2.15546,17962.166667,-6663.003333
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3,2.26403,18866.916667,-9669.423333
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7,0.87824,7318.666667,-5551.043333
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7,0.31570,2630.833333,-31532.186667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6,0.88530,7377.500000,-1077.920000
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6,2.05738,17144.833333,-16942.856667
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3,2.11994,17666.166667,-8852.573333
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3,0.30105,2508.750000,-18434.360000
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1,2.48332,20694.333333,-27816.986667

In [158]:
# Replace division by zero results with missing values
df.loc[df['Customer_AnnualIncome'] == 0, 'Balance_Income_Ratio'] = pd.NA

In [159]:
# Display first 10 rows
print(df[['Customer_AccountBalance', 'Customer_AnnualIncome', 'Balance_Income_Ratio']].head(10))

   Customer_AccountBalance  Customer_AnnualIncome  Balance_Income_Ratio
0                111350.85                44033.0              2.528805
1                254378.37               215546.0              1.180158
2                159975.42               226403.0              0.706596
3                295741.60                87824.0              3.367435
4                242423.78                31570.0              7.678929
5                180084.44                37087.0              4.855730
6                 99629.81                67229.0              1.481947
7                 61030.94               139914.0              0.436203
8                221707.97               153267.0              1.446547
9                 41126.84               139914.0              0.293944

In [161]:
df.to_csv("Exam_on_Pandas.csv")