# Hotel Dataset — 30 Data Cleaning Questions

## 1. Remove leading/trailing spaces from column names

In [7]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("C:\\Users\\deore\\Downloads\\Hotel_booking_dataset - Hotel_booking_dataset.csv")

df.columns
df.columns = df.columns.str.strip()

In [11]:
df.columns

Index(['Booking ID', 'Customer Name', 'Booking Date', 'City', 'Room Type',
       'Booking Channel', 'Customer Segment', 'Gender', 'Age', 'Room Nights',
       'Room Rate', 'Discount %', 'Rating', 'Guests', 'Is Member', 'Cancelled',
       'Payment Method', 'Gross Amount', 'Discount Amount', 'Final Amount',
       'Hotel Cost', 'Profit'],
      dtype='object')

## 2. Standardize all date formats into one consistent format (YYYY-MM-DD)

In [23]:
df["Booking Date"] = pd.to_datetime(
    df['Booking Date'],
    errors = 'coerce' ,
    format = 'mixed',
    dayfirst = True
)

In [30]:
df["Booking Date"] = pd.to_datetime(
    df['Booking Date'],
    errors = 'coerce' ,
    format = 'mixed',
    dayfirst = True
).dt.strftime('%Y-%m-%d')
df['Booking Date'].fillna('2025-05-17',inplace = True)

C:\Users\deore\AppData\Local\Temp\ipykernel_4460\3961093219.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Booking Date'].fillna('2025-05-17',inplace = True)

In [33]:
df['Booking Date'].value_counts()

Booking Date
2025-05-17    35
2025-01-10    14
2025-01-04    13
2025-08-08    12
2025-05-08    12
              ..
2025-07-23     1
2025-09-26     1
2025-11-12     1
2025-01-27     1
2025-01-17     1
Name: count, Length: 365, dtype: int64

## 3. Handle completely missing Customer Name values

In [36]:
df['Customer Name'].value_counts()

Customer Name
john doe         6
12345            5
unknown          4
JOHN DOE         4
John_Doe         4
                ..
Customer_1632    1
Customer_0725    1
Customer_0041    1
Customer_0658    1
Customer_0642    1
Name: count, Length: 1950, dtype: int64

In [37]:
df['Customer Name'].isna().sum()

np.int64(34)

In [38]:
df['Customer Name'] = df['Customer Name'].replace(
    ['N/A', 'NA', 'n/a', ''],
    pd.NA
)

In [39]:
df['Customer Name'].fillna('Unknown', inplace = True)

C:\Users\deore\AppData\Local\Temp\ipykernel_4460\2264792903.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer Name'].fillna('Unknown', inplace=True)

In [40]:
df['Customer Name'].isna().sum()

np.int64(0)

## 4. Fix inconsistent Gender values

In [43]:
df['Gender'] = df['Gender'].str.strip().str.lower()

In [44]:
df.head()

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17,Mumbai,Suite,Online,Premium,male,39,4,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629420,16901.386250,12676.243170
1,BKG00789,Customer_0789,2025-07-29,Bengaluru,Suite,Walk-in,Corporate,male,25,1,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19,Pune,Suite,Corporate,Corporate,other,50,4,...,1.2,1,0,1,Credit Card,66334.52,15575.345300,50759.174700,40212.657470,10546.517240
3,BKG01079,Customer_1079,2025-12-14,Mumbai,Deluxe,Walk-in,Regular,male,53,3,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806940,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20,Delhi,Suite,Travel Agent,Budget,male,38,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676

In [45]:
df['Gender'].value_counts()

Gender
female    1000
male       945
other       69
m            7
f            4
Name: count, dtype: int64

In [53]:
df['Gender'].replace({
    'm':'Male',
    'f':'Female',
    'male':'Male',
    'female':'Female',
    'other' : 'Other'})

0         Male
1         Male
2        Other
3         Male
4         Male
         ...
2020     Other
2021      Male
2022      Male
2023    Female
2024      Male
Name: Gender, Length: 2025, dtype: object

In [54]:
df['Gender'].value_counts()

Gender
Female    1004
Male       952
Other       69
Name: count, dtype: int64

In [55]:
df['Gender'].isna().sum()

np.int64(0)

## 5. Clean and standardize City names

In [60]:
df['City'].value_counts()

City
Delhi        360
Mumbai       351
Pune         335
Bengaluru    317
Chennai      309
Hyderabad    303
Bangalore      5
mumbai         4
Hydrabad       4
delhi          3
MUMBAI         3
bangalore      2
Name: count, dtype: int64

In [63]:
df['City'].replace({
    'delhi':'Delhi',
    'mumbai':'Mumbai',
    'MUMBAI':'Mumbai',
    'Bangalore':'Bengaluru',
    'Hydrabad':'Hyderabad',
    'bangalore':'Bengaluru'
},inplace =True)

In [64]:
df['City'].value_counts()

City
Delhi        363
Mumbai       358
Pune         335
Bengaluru    324
Chennai      309
Hyderabad    307
Name: count, dtype: int64

In [65]:
df['City'] = df['City'].str.strip().str.title()

In [67]:
df['City'].value_counts()
df.head()

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17,Mumbai,Suite,Online,Premium,Male,39,4,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629420,16901.386250,12676.243170
1,BKG00789,Customer_0789,2025-07-29,Bengaluru,Suite,Walk-in,Corporate,Male,25,1,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19,Pune,Suite,Corporate,Corporate,Other,50,4,...,1.2,1,0,1,Credit Card,66334.52,15575.345300,50759.174700,40212.657470,10546.517240
3,BKG01079,Customer_1079,2025-12-14,Mumbai,Deluxe,Walk-in,Regular,Male,53,3,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806940,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20,Delhi,Suite,Travel Agent,Budget,Male,38,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676

## 6. Standardize Room Type categories

In [68]:
df['Room Type'].value_counts()

Room Type
Deluxe       542
Executive    502
Suite        475
Standard     449
Unknown        7
delux          6
exec           4
suite          4
standard       3
STANDARD       2
Name: count, dtype: int64

In [73]:
df['Room Type']=df['Room Type'].replace({
    'delux' : 'Deluxe',
    'exec' :  'Executive',
    'suite': 'Suite',
    'standard' : 'Standard',
    'STANDARD' : 'Standard',
    'Unknown' : 'Deluxe'
})

In [74]:
df['Room Type'].value_counts()

Room Type
Deluxe       555
Executive    506
Suite        479
Standard     454
Name: count, dtype: int64

## 7. Clean Booking Channel values

In [83]:
df['Booking Channel'].value_counts()

Booking Channel
Online          555
Walk-in         527
Travel Agent    472
Corporate       467
Walk-in           4
Name: count, dtype: int64

In [87]:
df['Booking Channel']=df['Booking Channel'].str.strip()

In [88]:
df['Booking Channel']=df['Booking Channel'].replace({
    'ONLINE' : 'Online',
    'TravelAgent' :  'Travel Agent',
    'corp': 'Corporate',
    'walkin' : 'Walk-in',
    'online' : 'Online',
    'travel agent' : 'Travel Agent'
})

In [89]:
df['Booking Channel'].value_counts()

Booking Channel
Online          555
Walk-in         531
Travel Agent    472
Corporate       467
Name: count, dtype: int64

## 8. Standardize Customer Segment

In [90]:
df['Customer Segment'].value_counts()

Customer Segment
Budget       523
Premium      517
Regular      486
Corporate    477
regular        5
VIP            5
REG            5
corporate      3
premium        2
budget         2
Name: count, dtype: int64

In [93]:
df['Customer Segment'] = df['Customer Segment'].replace({
    'regular':'Regular',
    'VIP':'Premium',
    'REG':'Regular',
    'corporate':'Corporate',
    'premium':'Premium',
    'budget':'Budget'
})

In [94]:
df['Customer Segment'].value_counts()

Customer Segment
Budget       525
Premium      524
Regular      496
Corporate    480
Name: count, dtype: int64

## 9. Fix Age column (invalid and non-numeric values)

In [97]:

df['Age']=df['Age'].str.strip()
df['Age'].value_counts()

Age
20          54
62          51
26          49
65          48
61          45
69          45
34          45
27          44
39          44
38          42
59          42
50          42
44          41
58          41
54          41
60          40
51          40
36          40
23          40
46          40
22          40
67          40
48          40
64          40
32          39
31          38
24          38
18          38
53          37
56          36
37          36
25          36
63          34
47          34
28          34
49          34
68          34
35          34
29          33
19          33
55          32
41          32
42          32
21          31
33          31
52          31
57          30
40          29
45          29
30          26
66          26
43          23
150          7
25 years     7
120          6
unknown      6
100          5
30 yrs       5
45Y          3
Name: count, dtype: int64

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2025 entries, 0 to 2024
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Booking ID        2025 non-null   object
 1   Customer Name     2025 non-null   object
 2   Booking Date      2025 non-null   object
 3   City              1996 non-null   object
 4   Room Type         1994 non-null   object
 5   Booking Channel   2025 non-null   object
 6   Customer Segment  2025 non-null   object
 7   Gender            2025 non-null   object
 8   Age               1993 non-null   object
 9   Room Nights       2020 non-null   object
 10  Room Rate         1995 non-null   object
 11  Discount %        1990 non-null   object
 12  Rating            1987 non-null   object
 13  Guests            2025 non-null   int64
 14  Is Member         2025 non-null   object
 15  Cancelled         2025 non-null   object
 16  Payment Method    1995 non-null   object
 17  Gross Amount      2025 non-null   float64
 18  Discount Amount   2025 non-null   float64
 19  Final Amount      1995 non-null   float64
 20  Hotel Cost        2025 non-null   float64
 21  Profit            2025 non-null   float64
dtypes: float64(5), int64(1), object(16)
memory usage: 348.2+ KB

TypeError: '<' not supported between instances of 'str' and 'int'

In [101]:
df['Age'] = df['Age'].replace({
    '25 years' : 25,
    '30 yrs' : 30,
    '45Y' : 45,
    'unknown' :
})

In [102]:
df['Age'].value_counts()

Age
20     54
62     51
26     49
65     48
61     45
69     45
34     45
27     44
39     44
38     42
59     42
50     42
44     41
58     41
54     41
60     40
51     40
36     40
23     40
46     40
22     40
67     40
48     40
64     40
32     39
31     38
24     38
18     38
53     37
56     36
37     36
25     36
63     34
47     34
28     34
49     34
68     34
35     34
29     33
19     33
55     32
41     32
42     32
21     31
33     31
52     31
57     30
40     29
45     29
30     26
66     26
43     23
150     7
25      7
120     6
20      6
100     5
30      5
45      3
Name: count, dtype: int64

In [110]:

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

In [111]:
df.loc[(df['Age'] < 18) | (df['Age'] > 100), 'Age'] = np.nan

In [119]:
df['Age'] = df['Age'].astype('Int64')

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2025 entries, 0 to 2024
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Booking ID        2025 non-null   object
 1   Customer Name     2025 non-null   object
 2   Booking Date      2025 non-null   object
 3   City              1996 non-null   object
 4   Room Type         1994 non-null   object
 5   Booking Channel   2025 non-null   object
 6   Customer Segment  2025 non-null   object
 7   Gender            2025 non-null   object
 8   Age               1980 non-null   Int64
 9   Room Nights       2020 non-null   object
 10  Room Rate         1995 non-null   object
 11  Discount %        1990 non-null   object
 12  Rating            1987 non-null   object
 13  Guests            2025 non-null   int64
 14  Is Member         2025 non-null   object
 15  Cancelled         2025 non-null   object
 16  Payment Method    1995 non-null   object
 17  Gross Amount      2025 non-null   float64
 18  Discount Amount   2025 non-null   float64
 19  Final Amount      1995 non-null   float64
 20  Hotel Cost        2025 non-null   float64
 21  Profit            2025 non-null   float64
dtypes: Int64(1), float64(5), int64(1), object(15)
memory usage: 350.2+ KB

In [114]:
df['Age'].value_counts()

Age
20     60
62     51
26     49
65     48
34     45
69     45
61     45
39     44
27     44
25     43
50     42
38     42
59     42
58     41
54     41
44     41
22     40
60     40
67     40
46     40
51     40
36     40
48     40
23     40
64     40
32     39
18     38
31     38
24     38
53     37
37     36
56     36
35     34
63     34
49     34
68     34
47     34
28     34
29     33
19     33
42     32
41     32
45     32
55     32
33     31
21     31
30     31
52     31
57     30
40     29
66     26
43     23
100     5
Name: count, dtype: Int64

In [115]:
df['Age'].nunique

<bound method IndexOpsMixin.nunique of 0       39
1       25
2       50
3       53
4       38
        ..
2020    52
2021    33
2022    48
2023    52
2024    23
Name: Age, Length: 2025, dtype: Int64>

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2025 entries, 0 to 2024
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Booking ID        2025 non-null   object
 1   Customer Name     2025 non-null   object
 2   Booking Date      2025 non-null   object
 3   City              1996 non-null   object
 4   Room Type         1994 non-null   object
 5   Booking Channel   2025 non-null   object
 6   Customer Segment  2025 non-null   object
 7   Gender            2025 non-null   object
 8   Age               1980 non-null   Int64
 9   Room Nights       2020 non-null   object
 10  Room Rate         1995 non-null   object
 11  Discount %        1990 non-null   object
 12  Rating            1987 non-null   object
 13  Guests            2025 non-null   int64
 14  Is Member         2025 non-null   object
 15  Cancelled         2025 non-null   object
 16  Payment Method    1995 non-null   object
 17  Gross Amount      2025 non-null   float64
 18  Discount Amount   2025 non-null   float64
 19  Final Amount      1995 non-null   float64
 20  Hotel Cost        2025 non-null   float64
 21  Profit            2025 non-null   float64
dtypes: Int64(1), float64(5), int64(1), object(15)
memory usage: 350.2+ KB