In [32]:
import pandas as pd
df = pd.read_excel("C:\\Users\\deore\\Downloads\\Bank_customer_churn.xlsx")
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [33]:
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

# Q3 Show 7 random customer records.

In [34]:
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7957,7958,15582149,Ts'ui,850,Germany,Female,34,3,129668.43,2,1,1,88743.99,0
4381,4382,15680370,DeRose,492,France,Male,39,7,0.00,2,0,1,71323.23,0
1695,1696,15704250,Akabueze,506,France,Male,34,7,0.00,2,0,0,115842.10,0
9746,9747,15782550,Ma,490,Germany,Female,41,0,139659.04,1,1,1,176254.12,0
9518,9519,15714920,Balashov,585,Germany,Male,44,7,163867.86,1,1,1,112333.22,0
9382,9383,15665634,Campbell,645,France,Female,38,7,59568.57,1,1,1,167723.25,0
5144,5145,15748069,Clunie,485,France,Female,25,3,134467.26,1,1,1,113266.09,0

## Q4 Print complete dataset information and identify: 
• Total columns  
• Data type of each column  
• Missing values

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

## Q5 Find missing values in every column.

In [36]:
df.isnull()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Q6  Display only numerical columns.

In [37]:

num_df = df.select_dtypes(include = "number")
num_df

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

## Q7 Generate the statistical summary of numerical columns.

In [38]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

## Q8 Find duplicate rows and print how many exist.

In [39]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [40]:
df[df.duplicated()]

Empty DataFrame
Columns: [RowNumber, CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []

In [41]:
count = df.duplicated().sum()
print(count)

0

## Q9 Remove duplicate rows and store the cleaned dataset.

In [42]:
d = df.drop_duplicates()
print(d)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]

## Q10 Count how many customers have exited and how many have not exited.

In [43]:
# how much time unik value appers
count = df["Exited"].value_counts()
print(count)

Exited
0    7963
1    2037
Name: count, dtype: int64

## Medium Level (11–20)

## Q11 Rename the following columns: 
CustomerId → Customer_ID 
CreditScore → Credit_Score 
EstimatedSalary → Salary 
Exited → Churn

In [44]:
df = df.rename(columns={
    'CustomerId': 'Customer_ID',
    'CreditScore': 'Credit_Score',
    'EstimatedSalary': 'Salary',
    'Exited': 'Churn'
})

print(df.head())

   RowNumber  Customer_ID   Surname  Credit_Score Geography  Gender  Age  \
0          1     15634602  Hargrave           619    France  Female   42
1          2     15647311      Hill           608     Spain  Female   41
2          3     15619304      Onio           502    France  Female   42
3          4     15701354      Boni           699    France  Female   39
4          5     15737888  Mitchell           850     Spain  Female   43

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0       2       0.00              1          1               1  101348.88
1       1   83807.86              1          0               1  112542.58
2       8  159660.80              3          1               0  113931.57
3       1       0.00              2          0               0   93826.63
4       2  125510.82              1          1               1   79084.10

   Churn
0      1
1      0
2      1
3      0
4      0

In [45]:
df = pd.read_excel("C:\\Users\\deore\\Downloads\\Bank_customer_churn.xlsx")

In [46]:
df.rename(columns={
    'CustomerId': 'Customer_ID',
    'CreditScore': 'Credit_Score',
    'EstimatedSalary': 'Salary',
    'Exited': 'Churn'
})

print(df.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0

## Q12 Add the prefix Bank_ to every column name.

In [50]:
import pandas as pd
df  = df.add_prefix('Bank_')
print(df.head())

   Bank_RowNumber  Bank_CustomerId Bank_Surname  Bank_CreditScore  \
0               1         15634602     Hargrave               619
1               2         15647311         Hill               608
2               3         15619304         Onio               502
3               4         15701354         Boni               699
4               5         15737888     Mitchell               850

  Bank_Geography Bank_Gender  Bank_Age  Bank_Tenure  Bank_Balance  \
0         France      Female      42.0            2          0.00
1          Spain      Female      41.0            1      83807.86
2         France      Female      42.0            8     159660.80
3         France      Female      39.0            1          0.00
4          Spain      Female      43.0            2     125510.82

   Bank_NumOfProducts  Bank_HasCrCard  Bank_IsActiveMember  \
0                   1               1                    1
1                   1               0                    1
2                   3               1                    0
3                   2               0                    0
4                   1               1                    1

   Bank_EstimatedSalary  Bank_Exited
0             101348.88            1
1             112542.58            0
2             113931.57            1
3              93826.63            0
4              79084.10            0

## Q13 Convert the Age column into float datatype.

In [49]:
df['Bank_Age'] = df['Bank_Age'].astype(float)
print(df['Bank_Age'].dtype)

float64

## Q14 Convert the Exited column into string datatype.

In [51]:
df['Bank_Exited'] =  df['Bank_Exited'].astype(str)
print(df['Bank_Exited'].dtype)

object

## Q15 Suppose the Balance column has missing values. Replace them using the mean of the Balance column.

In [53]:
df['Bank_Balance'] = df['Bank_Balance'].fillna(df['Bank_Balance'].mean())
print(df['Bank_Balance'].head())

0         0.00
1     83807.86
2    159660.80
3         0.00
4    125510.82
Name: Bank_Balance, dtype: float64

In [54]:
df['Bank_Age'] = df['Bank_Age'].fillna(df['Bank_Age'].median())
print(df['Bank_Age'].head())

0    42.0
1    41.0
2    42.0
3    39.0
4    43.0
Name: Bank_Age, dtype: float64

## Q17  Display only the first five rows after renaming the columns.