## Challenge 1 – Complete Data Cleaning

In [14]:
# import pandas library
import pandas as pd
# load data data frame
df = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df = pd.DataFrame(df)
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn

In [16]:
# display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [4]:
# find null values 
df.isna()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1015,False,False,False,False,False,False,False,False,False,False,False
1016,False,False,False,False,False,False,False,False,True,False,False
1017,False,False,False,False,False,False,False,False,False,False,False
1018,False,False,True,False,False,False,False,False,False,False,False
1019,False,False,False,False,False,True,False,False,False,True,False

In [7]:
# remove duplicate rowes
df.drop_duplicates(inplace=True)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [24]:
# fill the median in null value  in age column
df.fillna({ 'Age': df['Age'].median(), 
            'Balance': df['Balance'].mean() 
          }, 
          inplace=True)
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

In [11]:
# rename the Target --> CustomerStatus and Anuualincome --> Income
df.rename(columns = { 'Target': 'CustomerStatus',
                      'AnnualIncome' : 'Income'
                    },
          inplace = True)

In [13]:
# print first 15 rows of the data frame
df.head(15)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

## Challenge 2 – Banking Report

In [19]:
# import pandas library
import pandas as pd
# load data data frame
df2 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df2 = pd.DataFrame(df2)

In [23]:
# select only numeric coloumns
numaric_df = df2.select_dtypes(include = 'number')
numaric_df

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure
0          10001  58.0       49184.0      2139          581        NaN       2
1          10002  65.0      162964.0      6197          732    6356.54       1
2          10003  56.0       26956.0     37281          503  143203.92       8
3          10004  55.0       92926.0       925          463  139627.88       5
4          10005  66.0      108236.0      7198          394   75985.46       5
...          ...   ...           ...       ...          ...        ...     ...
1015       10450  43.0      173620.0      7121          644   60353.03       2
1016       10753  25.0       54490.0     13794          303  124512.07       4
1017       10810  49.0       82062.0     47170          813   53850.09       8
1018       10267  38.0           NaN     10424          722  138100.05       6
1019       10059  62.0       97504.0     36833          430        NaN      10

[1020 rows x 7 columns]

In [25]:
# display summery status
df2.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [33]:
# Convert Age and CreditScore to float.  

df2[['Age','CreditScore']] = df2[['Age','CreditScore']].astype(float)

# Display information again. 
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   float64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

## Challenge 3 – Duplicate Investigation

In [38]:
# import pandas library
import pandas as pd
# load data data frame
df3 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df3 = pd.DataFrame(df3)

In [40]:
# Count duplicate rows.  
cound =df3.duplicated().sum()

np.int64(20)

In [44]:
# information before removing duplicates
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [47]:
#  Remove duplicates.  
df3.drop_duplicates(inplace = True )

In [46]:
# Print information  after removing duplicates. 
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [48]:
df3.duplicated().sum()

np.int64(0)

# Show the last 20 rows.

In [49]:
df3.tail()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

## Challenge 4 – HR Department

In [56]:
# import pandas library
import pandas as pd
# load data data frame
df4 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df4 = pd.DataFrame(df4)

In [59]:


df4.rename(columns = {'Age' : 'EmployeeAge',
                      'Gender' :'EmployeeGender', 
                      'AnnualIncome' :'Salary' ,
                      'Target' :'PromotionStatus'},inplace = True)
df4

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [68]:
# Then • Add prefix  HR_ 
df4.columns = ["HR_" + col for col in df4.columns ] # using add_prefix also possible

In [70]:
# Display 10 random records. 
df4.sample(10)

,HR_CustomerID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
339,10340,66.0,90717.0,7199,435,17459.45,6,Canada,Other,SME,Churn
382,10383,26.0,54784.0,16862,449,142278.97,3,France,Female,Corporate,Churn
72,10073,67.0,173112.0,46081,320,171346.41,9,Canada,Female,Retail,Churn
896,10897,46.0,88264.0,24726,488,41031.07,0,France,Female,Corporate,Churn
780,10781,65.0,101914.0,1973,891,151698.76,10,USA,Female,Retail,Stay
901,10902,26.0,197735.0,36607,419,61616.44,6,Germany,Male,Corporate,Churn
854,10855,53.0,63255.0,29248,549,185135.11,0,USA,NaN,SME,Churn
970,10971,45.0,130629.0,42896,337,40398.10,4,USA,Male,Corporate,Churn
426,10427,65.0,105524.0,21344,763,54391.17,1,USA,Male,SME,Churn
220,10221,47.0,145444.0,41901,486,162299.54,1,France,Female,Retail,Churn

## Challenge 5 – Finance Cleaning

In [83]:
# import pandas library
import pandas as pd
# load data data frame
df5 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df5 = pd.DataFrame(df5)

In [84]:
df5.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn

In [88]:
# fill the null value with median , mean, median
df5.fillna({'AnnualIncome' : df5['AnnualIncome'].median(),
'Balance' :df5['Balance'].mean(),
'Age' : df5['Age'].median()}, inplace = True)

In [91]:
df5.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

## Challenge 6 – Data Type Audit

In [100]:
# import pandas library
import pandas as pd
# load data data frame
df6 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df6 = pd.DataFrame(df6)

df6['Age'].isnull().sum()
df6.fillna({'Age' : df6['Age'].mean()},inplace = True)

In [102]:
# covert age --> int
df6['Age'] = df6['Age'].astype(int)

In [104]:
df6['AnnualIncome'] = df6['AnnualIncome'].astype(float)

In [105]:
df6['Target'] = df6['Target'].astype(str)

In [107]:
print(df6.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB
None

## Challenge 7 – Customer Analytics

In [2]:
# import pandas library
import pandas as pd
# load data data frame
df7 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df7 = pd.DataFrame(df7)

In [3]:
# Remove Segment column
df7.drop('Segment', axis=1, inplace=True)

# Remove Geography column
df7.drop('Geography', axis=1, inplace=True)

# Remove duplicate rows
df7.drop_duplicates(inplace=True)

In [4]:
# first 10 rows
df7.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Gender,Target
0,10001,58.0,49184.0,2139,581,NaN,2,Male,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,Male,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Male,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,Male,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,Other,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,Other,Stay
6,10007,58.0,182141.0,24200,891,38457.72,1,Other,Churn
7,10008,67.0,95861.0,5729,538,173296.73,6,Female,Stay
8,10009,41.0,62638.0,24760,663,41901.41,4,Other,Stay
9,10010,22.0,179680.0,42113,475,106827.98,3,Female,Churn

In [5]:
# dataset information
df7.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Gender        950 non-null    object
 8   Target        1000 non-null   object
dtypes: float64(3), int64(4), object(2)
memory usage: 78.1+ KB

In [6]:
df7.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,950.000000,950.000000,1000.000000,1000.000000,950.000000,1000.000000
mean,10500.500000,44.212632,112458.303158,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.524244,52409.868404,14211.735656,176.605486,55845.536430,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,30.000000,65922.500000,13213.000000,441.000000,50003.880000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,95174.625000,5.000000
75%,10750.250000,58.000000,157973.000000,37960.250000,758.250000,144198.130000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

## Challenge 8 – ML Dataset

In [7]:
# import pandas library
import pandas as pd
# load data data frame
df8 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df8 = pd.DataFrame(df8)

In [8]:
df8.drop_duplicates(inplace = True)

In [9]:
# Remove CustomerID
df8.drop("CustomerID" , axis = 1 , inplace = True)

In [10]:
# Remove Segment
df8.drop("Segment" ,axis = 1, inplace = True)

In [16]:
# fill missing values
df8.fillna({'Age':df8['Age'].mean()},inplace = True)

In [18]:
# head()

df8.head()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Target
0,58.0,49184.0,2139,581,NaN,2,France,Male,Stay
1,65.0,162964.0,6197,732,6356.54,1,USA,Male,Churn
2,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Stay
3,55.0,92926.0,925,463,139627.88,5,NaN,Male,Churn
4,66.0,108236.0,7198,394,75985.46,5,UK,Other,Churn

In [20]:
# info()

df8.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           1000 non-null   float64
 1   AnnualIncome  950 non-null    float64
 2   Spending      1000 non-null   int64
 3   CreditScore   1000 non-null   int64
 4   Balance       950 non-null    float64
 5   Tenure        1000 non-null   int64
 6   Geography     950 non-null    object
 7   Gender        950 non-null    object
 8   Target        1000 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 78.1+ KB

In [21]:
# describe()
df8.describe()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,950.000000,1000.000000,1000.000000,950.000000,1000.000000
mean,44.212632,112458.303158,25285.558000,603.088000,97557.565779,5.241000
std,15.130763,52409.868404,14211.735656,176.605486,55845.536430,3.179155
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,31.000000,65922.500000,13213.000000,441.000000,50003.880000,2.000000
50%,44.212632,112347.500000,24901.000000,606.500000,95174.625000,5.000000
75%,57.000000,157973.000000,37960.250000,758.250000,144198.130000,8.000000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [23]:
df8['Age'].value_counts()

Age
44.212632    50
27.000000    33
69.000000    26
44.000000    26
37.000000    25
66.000000    25
26.000000    24
38.000000    23
58.000000    22
53.000000    22
21.000000    22
61.000000    22
25.000000    21
67.000000    21
47.000000    21
70.000000    21
46.000000    20
51.000000    20
34.000000    19
50.000000    19
62.000000    18
31.000000    18
32.000000    18
24.000000    18
30.000000    18
40.000000    18
57.000000    17
52.000000    17
68.000000    17
20.000000    17
59.000000    17
45.000000    17
41.000000    17
64.000000    17
43.000000    17
33.000000    16
19.000000    16
65.000000    16
18.000000    15
29.000000    15
48.000000    15
23.000000    15
55.000000    15
36.000000    15
63.000000    14
56.000000    13
28.000000    13
49.000000    13
54.000000    13
22.000000    12
35.000000    12
42.000000    10
39.000000    10
60.000000     9
Name: count, dtype: int64

## Challenge 9 – Column

In [36]:
# import pandas library
import pandas as pd
# load data data frame
df9 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df9 = pd.DataFrame(df9)


df9.fillna({'Balance': df9['Balance'].mean()},inplace = True)

In [38]:
df9['NetWorth'] = df9['Balance'] + df9['AnnualIncome']
df9['AgeAfterRetirement'] = df9['Age'] + 20
df9['DoubleCreditScore'] = df9['CreditScore'] * 2
df9['IncomePerMonth'] = df9['AnnualIncome'] / 12
df9.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,146707.535666,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,169320.540000,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,170159.920000,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,232553.880000,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,184221.460000,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay,138635.620000,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn,220598.720000,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay,269157.730000,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay,104539.410000,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn,286507.980000,42.0,950,14973.333333
10,10011,NaN,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay,231695.030000,NaN,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn,115931.720000,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay,179444.320000,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay,174562.770000,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn,304725.430000,46.0,786,12797.416667

# Challenge 10 – Company

In [42]:
# import pandas library
import pandas as pd
# load data data frame
df10 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df10 = pd.DataFrame(df10)

In [44]:
# first five rows
df10.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [45]:
# last five rows  
df10.tail()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [48]:
# ten random rows  
df10.sample(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
446,10447,NaN,177722.0,14839,320,105289.70,0,UK,Other,Retail,Churn
810,10811,20.0,168937.0,32171,677,22632.87,7,France,Male,Retail,Stay
105,10106,44.0,138096.0,45678,781,58251.86,3,NaN,Other,Corporate,Stay
924,10925,51.0,NaN,11785,611,5751.91,1,USA,Male,SME,Churn
863,10864,69.0,138789.0,3338,406,148083.38,8,USA,Male,Retail,Churn
97,10098,41.0,67039.0,20309,314,141603.70,2,UK,Male,Retail,Churn
171,10172,29.0,91636.0,46552,616,184307.50,5,India,Male,Retail,Stay
772,10773,27.0,93520.0,2542,647,196723.75,10,Germany,Male,SME,Stay
533,10534,53.0,188641.0,25314,712,163420.66,1,Canada,NaN,SME,Churn
282,10283,18.0,108371.0,19834,881,134880.23,3,USA,Other,SME,Stay

In [49]:
# dataset information  
df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [50]:
#  descriptive statistics  
df10.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [51]:
df10.rename(columns = { 'Target' : 'Customer_Status'},inplace = True)

In [52]:
df10

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

## Challenge 11 – Missing Value Report

In [2]:
# import pandas library
import pandas as pd
# load data data frame
df11 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df11 = pd.DataFrame(df11)

In [22]:
# total missing values

Total_Missing_values = df11.isna().sum()
Total_Missing_values

CustomerID       0
Age              0
AnnualIncome    53
Spending         0
CreditScore      0
Balance          0
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [5]:
# Numerical columns

numeric_cols = df11.select_dtypes(include = 'number').columns.tolist()

In [10]:
# mean of balance
mean = df11['Balance'].mean()

In [13]:
# median of Age
median = df11['Age'].median()

In [18]:
# fill missing values 
df11.fillna({'Balance' : df11['Balance'].mean(), 'Age' : df11['Age'].median()},inplace =True )

In [24]:
# display all information
print("Total missing values :",Total_Missing_values)
print("Numerical colums are:")
for i in numeric_cols:
    print(i,end =",")

print("\n")
print("Mean of Balance columne :",mean)
print("Median of Age columne :",median)

Total missing values : CustomerID       0
Age              0
AnnualIncome    53
Spending         0
CreditScore      0
Balance          0
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64
Numerical colums are:
CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,

Mean of Balance columne : 97523.53566563467
Median of Age columne : 44.0

## Challenge 12 – Customer Classification

In [25]:
# import pandas library
import pandas as pd
# load data data frame
df12 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df12 = pd.DataFrame(df12)

In [29]:
# cout stay and churn
df12['Target'].value_counts()

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [31]:
# rename targe --> Customer_class
df12.rename(columns = {'Target' : 'Customer_Class'},inplace = True)

In [36]:
# convert it into string
df12['Customer_Class'] = df12['Customer_Class'].astype(str)
df12['Customer_Class'].dtype

dtype('O')

## Challenge 13 – Sales Department

In [9]:
# import pandas library
import pandas as pd
# load data data frame
df13 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df13 = pd.DataFrame(df13)

In [10]:
# rename 
df13.rename(columns = {'Balance' :'AccountBalance',
                       'AnnualIncome':'Salary',
                       'CreditScore':'Score'},
                        inplace = True)

In [11]:
# add Prefix

df13 = df13.add_prefix("Sales_")

In [12]:
# display 

df13.sample(20)

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
109,10110,37.0,125515.0,18341,812,107996.31,7,India,Other,Retail,Stay
236,10237,37.0,61289.0,47149,478,158739.28,8,NaN,Male,Retail,Churn
462,10463,53.0,148699.0,10565,355,72165.78,6,India,Female,SME,Churn
970,10971,45.0,130629.0,42896,337,40398.10,4,USA,Male,Corporate,Churn
229,10230,69.0,198103.0,10984,331,28555.89,9,France,Female,Retail,Churn
115,10116,25.0,125952.0,34224,301,131532.08,8,NaN,Female,Retail,Churn
774,10775,20.0,91171.0,27623,388,99410.89,3,UK,Female,Corporate,Churn
132,10133,27.0,84014.0,35310,721,113185.61,2,USA,Male,NaN,Stay
728,10729,27.0,109597.0,26245,440,17559.00,6,Germany,Other,SME,Churn
977,10978,52.0,118226.0,46350,415,63297.99,6,Canada,Other,NaN,Churn
947,10948,52.0,24632.0,2570,740,176025.13,1,NaN,Female,Corporate,Churn
452,10453,18.0,170165.0,26163,881,6476.55,9,NaN,Other,Retail,Churn
541,10542,47.0,69959.0,47475,646,21553.15,6,India,Other,SME,Stay
444,10445,38.0,114052.0,39268,328,140690.58,5,Germany,Other,Retail,Churn
373,10374,49.0,63844.0,5917,878,6172.14,3,UK,Male,Corporate,Churn
206,10207,34.0,33678.0,42520,792,NaN,8,India,Other,SME,Stay
897,10898,27.0,117757.0,29888,852,195093.14,8,UK,Male,Retail,Stay
105,10106,44.0,138096.0,45678,781,58251.86,3,NaN,Other,Corporate,Stay
375,10376,50.0,49677.0,38033,416,53577.78,8,UK,Other,Retail,Churn
183,10184,23.0,134481.0,7437,549,87135.31,6,Germany,Male,Corporate,Stay

## Challenge 14 – Interview Challenge

In [14]:
df13.duplicated().sum()

np.int64(20)

In [18]:
# remove duplicates rows from data frame
df13.drop_duplicates(inplace = True)

In [19]:
df13.duplicated().sum()

np.int64(0)

In [20]:
# rename Target 
df13.rename(columns = {'Sales_Target':'Target'},inplace = True)

In [21]:
df13.head()

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [22]:
df13.isna().sum()

Sales_CustomerID         0
Sales_Age               50
Sales_Salary            50
Sales_Spending           0
Sales_Score              0
Sales_AccountBalance    50
Sales_Tenure             0
Sales_Geography         50
Sales_Gender            50
Sales_Segment           50
Target                   0
dtype: int64

In [ ]:
df13.info()

In [32]:
# fill mean of sales_Age column in null values
df13.fillna({'Sales_Age':df13['Sales_Age'].mean()},inplace = True)

In [33]:
df13['Sales_Age'] = df13['Sales_Age'].astype(int)
df13.head()

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Target
0,10001,58,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [34]:
df13.fillna({'Sales_AccountBalance':df13['Sales_AccountBalance'].mean()},inplace = True)

In [35]:
# convert Balance to float
df13['Sales_AccountBalance']=df13['Sales_AccountBalance'].astype(float)

In [36]:
# display summary
df13.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Sales_CustomerID      1000 non-null   int64
 1   Sales_Age             1000 non-null   int64
 2   Sales_Salary          950 non-null    float64
 3   Sales_Spending        1000 non-null   int64
 4   Sales_Score           1000 non-null   int64
 5   Sales_AccountBalance  1000 non-null   float64
 6   Sales_Tenure          1000 non-null   int64
 7   Sales_Geography       950 non-null    object
 8   Sales_Gender          950 non-null    object
 9   Sales_Segment         950 non-null    object
 10  Target                1000 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 93.8+ KB

## Challenge 15 – Data Engineer Task

In [48]:
# import pandas library
import pandas as pd
# load data data frame
df15 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df15 = pd.DataFrame(df15)

In [49]:
# created df14 dataframe containing only numeric columns of df15
df14 = df15.select_dtypes(include='number')
df14.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
dtypes: float64(3), int64(4)
memory usage: 55.9 KB

In [50]:
# drop CustomerID and Target
df14.drop('CustomerID',axis = 1 ,inplace =True)

In [51]:
# drop Target from df15 dataframe
df15.drop('Target',axis = 1,inplace =True)

In [52]:
df15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
dtypes: float64(3), int64(4), object(3)
memory usage: 79.8+ KB

In [53]:
df14.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           970 non-null    float64
 1   AnnualIncome  967 non-null    float64
 2   Spending      1020 non-null   int64
 3   CreditScore   1020 non-null   int64
 4   Balance       969 non-null    float64
 5   Tenure        1020 non-null   int64
dtypes: float64(3), int64(3)
memory usage: 47.9 KB

## Challenge 16 – Mixed Cleaning

In [57]:
# import pandas library
import pandas as pd
# load data data frame
df16 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df16 = pd.DataFrame(df16)

In [58]:
df16.duplicated().sum()

np.int64(20)

In [60]:
df16.drop_duplicates(inplace = True)
df16.duplicated().sum()

np.int64(0)

In [61]:
df16.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [64]:
# fill the value in null place of dataset
df16.fillna({'Age': 0.0,
             'AnnualIncome':0.0,
             'Balance':0.0,
             'Geography':"Unknown",
             'Gender':'Unknown',
             'Segment':'Unknown'},inplace = True)

In [65]:
df16.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   float64
 2   AnnualIncome  1000 non-null   float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       1000 non-null   float64
 6   Tenure        1000 non-null   int64
 7   Geography     1000 non-null   object
 8   Gender        1000 non-null   object
 9   Segment       1000 non-null   object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [66]:
# change the type of the coloumn age 
df16['Age'] = df16['Age'].astype(int)

In [67]:
# rename the Gender ---> sex
df16.rename(columns = {'Gender':'Sex'},inplace = True)

In [68]:
df16.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Sex,Segment,Target
0,10001,58,49184.0,2139,581,0.00,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.88,5,Unknown,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [70]:
# summery of the dataframe
df16.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   int64
 2   AnnualIncome  1000 non-null   float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       1000 non-null   float64
 6   Tenure        1000 non-null   int64
 7   Geography     1000 non-null   object
 8   Sex           1000 non-null   object
 9   Segment       1000 non-null   object
 10  Target        1000 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 93.8+ KB

## Challenge 17 – Real Company

In [71]:
# import pandas library
import pandas as pd
# load data data frame
df17 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df17 = pd.DataFrame(df17)

In [74]:
df17.duplicated().sum()

np.int64(20)

In [76]:
# remove all duplicaterecords
df17.drop_duplicates(inplace =True)

In [77]:
df17.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [79]:
# fill the value in null place of dataset
df17.fillna({'Age': 0.0,
             'AnnualIncome':0.0,
             'Balance':0.0,
             'Geography':"Unknown",
             'Gender':'Unknown',
             'Segment':'Unknown'},inplace = True)

In [80]:
df17.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   float64
 2   AnnualIncome  1000 non-null   float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       1000 non-null   float64
 6   Tenure        1000 non-null   int64
 7   Geography     1000 non-null   object
 8   Gender        1000 non-null   object
 9   Segment       1000 non-null   object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [86]:
# add company_ prefix
df17 = df17.add_prefix("Company_")

In [87]:
# display summery
df17.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company_CustomerID    1000 non-null   int64
 1   Company_Age           1000 non-null   float64
 2   Company_AnnualIncome  1000 non-null   float64
 3   Company_Spending      1000 non-null   int64
 4   Company_CreditScore   1000 non-null   int64
 5   Company_Balance       1000 non-null   float64
 6   Company_Tenure        1000 non-null   int64
 7   Company_Geography     1000 non-null   object
 8   Company_Gender        1000 non-null   object
 9   Company_Segment       1000 non-null   object
 10  Company_Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [89]:
df17['Company_Target'].value_counts()

Company_Target
Churn    506
Stay     494
Name: count, dtype: int64

## Challenge 18 – Customer Summary

In [106]:
# import pandas library
import pandas as pd
# load data data frame
df18 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df18 = pd.DataFrame(df18)

In [107]:
# Generater mean Balance
MB = df18['Balance'].mean()

In [108]:
# Generate median CreditScore
MDB = df18['CreditScore'].median()

In [111]:
# Generate mean Age
MA = df18['Age'].mean()
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [110]:
# Generate Median AnnualIncome
MDA = df18['AnnualIncome'].median()
print(df18['Balance'].isna().sum())
print(df18['CreditScore'].isna().sum())

51
0

In [112]:
# fill missing values using these statistics
df18.fillna({'Balance':MB,
            
            'Age':MA,
            'AnnualIncome':MDA},inplace =True)

In [113]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

# Challenge 19 – Transformation Challenge

In [114]:
# import pandas library
import pandas as pd
# load data data frame
df19 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df19 = pd.DataFrame(df19)

In [117]:
# convert in lacks 
df19['Income_in_Lakhs'] = df19['AnnualIncome']/100000
df19['Balance_in_Lakhs '] = df19['Balance']/100000
df19['SeniorCitizen'] = df19['Age']+0
df19['HighCreditScore'] = df19['CreditScore']*1

In [118]:
df19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         1020 non-null   int64
 1   Age                970 non-null    float64
 2   AnnualIncome       967 non-null    float64
 3   Spending           1020 non-null   int64
 4   CreditScore        1020 non-null   int64
 5   Balance            969 non-null    float64
 6   Tenure             1020 non-null   int64
 7   Geography          969 non-null    object
 8   Gender             968 non-null    object
 9   Segment            969 non-null    object
 10  Target             1020 non-null   object
 11  Income_in_Lakhs    967 non-null    float64
 12  Balance_in_Lakhs   969 non-null    float64
 13  SeniorCitizen      970 non-null    float64
 14  HighCreditScore    1020 non-null   int64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

## Challenge 20 – Final Interview Project

In [125]:
import pandas as pd
df20 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")

In [126]:
df20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [128]:
# find mssing values 

df20.isna().sum()

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [131]:
# remove duplicates 
df20.drop_duplicates(inplace = True)
df20.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [133]:
# renames the columns

# CustomerID --> Customer_ID
df20.rename(columns = {'CustomerID':'Customer_ID'},inplace = True)

# AnnualIncome --> Annual_Income
df20.rename(columns = {'AnnualIncome':'Annual_Income'},inplace = True)

# CreditScore --> Credit_Score
df20.rename(columns = {'CreditScore':'Credit_Score'},inplace = True)

# Target --> Customer_Status
df20.rename(columns = {'Target':'Customer_Status'},inplace = True)

In [134]:
df20.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      1000 non-null   int64
 1   Age              950 non-null    float64
 2   Annual_Income    950 non-null    float64
 3   Spending         1000 non-null   int64
 4   Credit_Score     1000 non-null   int64
 5   Balance          950 non-null    float64
 6   Tenure           1000 non-null   int64
 7   Geography        950 non-null    object
 8   Gender           950 non-null    object
 9   Segment          950 non-null    object
 10  Customer_Status  1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [138]:
df20.fillna({'Age':0.0,
            'Annual_Income':0.0,
            'Balance':0.0},inplace = True)

In [140]:
# convert float to int 

df20[['Age','Annual_Income','Balance']] = (df20[['Age','Annual_Income','Balance']].astype(int))
df20.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      1000 non-null   int64
 1   Age              1000 non-null   int64
 2   Annual_Income    1000 non-null   int64
 3   Spending         1000 non-null   int64
 4   Credit_Score     1000 non-null   int64
 5   Balance          1000 non-null   int64
 6   Tenure           1000 non-null   int64
 7   Geography        950 non-null    object
 8   Gender           950 non-null    object
 9   Segment          950 non-null    object
 10  Customer_Status  1000 non-null   object
dtypes: int64(7), object(4)
memory usage: 93.8+ KB

In [141]:
# fill missing values 
df20.fillna({'Segment':'Unknown',
            'Customer_ID': 0}, inplace = True)

In [146]:
# Create new columns 
df20['TotalMoney'] = df20['Balance'] + df20['Annual_Income']
df20['AgeAfter5Years'] = df20['Age'] + 5
df20['MonthlyIncome'] = df20['Annual_Income']/12
df20['CreditScoreDouble'] = df20['Credit_Score'] * 2

In [147]:
# display
df20.head()

,Customer_ID,Age,Annual_Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Segment,Customer_Status,TotalMoney,AgeAfter5Years,MonthlyIncome,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,10001,58,49184,2139,581,0,2,France,Male,SME,Stay,49184,63,4098.666667,63,4098.666667,1162
1,10002,65,162964,6197,732,6356,1,USA,Male,SME,Churn,169320,70,13580.333333,70,13580.333333,1464
2,10003,56,26956,37281,503,143203,8,Canada,Male,Corporate,Stay,170159,61,2246.333333,61,2246.333333,1006
3,10004,55,92926,925,463,139627,5,NaN,Male,Retail,Churn,232553,60,7743.833333,60,7743.833333,926
4,10005,66,108236,7198,394,75985,5,UK,Other,Corporate,Churn,184221,71,9019.666667,71,9019.666667,788

In [148]:
# tail
df20.tail()

,Customer_ID,Age,Annual_Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Segment,Customer_Status,TotalMoney,AgeAfter5Years,MonthlyIncome,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
995,10996,34,81731,40980,761,181465,5,Germany,Other,SME,Stay,263196,39,6810.916667,39,6810.916667,1522
996,10997,47,42475,1176,780,26640,5,France,Female,SME,Stay,69115,52,3539.583333,52,3539.583333,1560
997,10998,31,120531,46929,733,147220,4,India,Male,SME,Stay,267751,36,10044.250000,36,10044.250000,1466
998,10999,21,33661,22314,540,94186,5,NaN,Other,SME,Stay,127847,26,2805.083333,26,2805.083333,1080
999,11000,63,31930,851,559,100908,6,UK,Female,Unknown,Stay,132838,68,2660.833333,68,2660.833333,1118

In [149]:
# sample
df20.sample()

,Customer_ID,Age,Annual_Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Segment,Customer_Status,TotalMoney,AgeAfter5Years,MonthlyIncome,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
132,10133,27,84014,35310,721,113185,2,USA,Male,Unknown,Stay,197199,32,7001.166667,32,7001.166667,1442

In [150]:
# describe
df20.describe()

,Customer_ID,Age,Annual_Income,Spending,Credit_Score,Balance,Tenure,TotalMoney,AgeAfter5Years,MonthlyIncome,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,42.002000,106835.388000,25285.558000,603.088000,92679.217000,5.241000,199514.60500,47.002000,8902.949000,47.002000,8902.949000,1206.176000
std,288.819436,17.941123,56662.551688,14211.735656,176.605486,58439.365883,3.179155,79924.09352,17.941123,4721.879307,17.941123,4721.879307,353.210972
min,10001.000000,0.000000,0.000000,537.000000,300.000000,0.000000,0.000000,0.00000,5.000000,0.000000,5.000000,0.000000,600.000000
25%,10250.750000,28.000000,60393.750000,13213.000000,441.000000,43913.250000,2.000000,145210.75000,33.000000,5032.812500,33.000000,5032.812500,882.000000
50%,10500.500000,43.000000,107245.000000,24901.000000,606.500000,92217.000000,5.000000,200678.00000,48.000000,8937.083333,48.000000,8937.083333,1213.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.000000,8.000000,254433.75000,62.000000,12964.229167,62.000000,12964.229167,1516.500000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.000000,10.000000,390628.00000,75.000000,16663.916667,75.000000,16663.916667,1800.000000

In [154]:
# target counts
df20['Customer_Status'].value_counts()

Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

In [155]:
# final information
df20.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1000 non-null   int64
 1   Age                1000 non-null   int64
 2   Annual_Income      1000 non-null   int64
 3   Spending           1000 non-null   int64
 4   Credit_Score       1000 non-null   int64
 5   Balance            1000 non-null   int64
 6   Tenure             1000 non-null   int64
 7   Geography          950 non-null    object
 8   Gender             950 non-null    object
 9   Segment            1000 non-null   object
 10  Customer_Status    1000 non-null   object
 11  TotalMoney         1000 non-null   int64
 12  AgeAfter5Years     1000 non-null   int64
 13  MonthlyIncome      1000 non-null   float64
 14  AgeAfter5Years     1000 non-null   int64
 15  MonthlyIncome      1000 non-null   float64
 16  CreditScoreDouble  1000 non-null   int64
dtypes: float64(2), int64(11), object(4)
memory usage: 140.6+ KB